In [4]:
import numpy as np

def simple_conv2d(input_image, filter_kernel):
    """
    Perform a simple 2D convolution (valid/no padding, stride=1) of a single filter on input image.
    
    Parameters:
        input_image (numpy.ndarray): 2D array representing the grayscale image
        filter_kernel (numpy.ndarray): 2D array representing the filter/kernel
    
    Returns:
        output (numpy.ndarray): 2D array result after convolution
    """
    # Get dimensions
    image_h, image_w = input_image.shape
    filter_h, filter_w = filter_kernel.shape

    # Output dimensions (valid)
    output_h = image_h - filter_h + 1
    output_w = image_w - filter_w + 1

    # Initialize output
    output = np.zeros((output_h, output_w), dtype=np.float32)

    # Convolution operation (no padding, stride=1)
    for i in range(output_h):
        for j in range(output_w):
            # Extract current patch
            patch = input_image[i:i+filter_h, j:j+filter_w]
            # Apply filter and sum
            output[i, j] = np.sum(patch * filter_kernel)
    return output

In [6]:
# Example usage:
input_image = np.array([
    [1, 2, 3, 0, 1, 2],
    [4, 5, 6, 1, 1, 0],
    [7, 8, 9, 0, 2, 1],
    [1, 3, 5, 7, 9, 2],
    [2, 4, 6, 8, 0, 4],
    [0, 1, 2, 3, 4, 5]
], dtype=np.float32)

filter_kernel = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
], dtype=np.float32)

In [7]:

output = simple_conv2d(input_image, filter_kernel)
print("Output Feature Map:\n", output)


Output Feature Map:
 [[ -6.  14.  14.  -2.]
 [ -8.   8.   8.   5.]
 [-10.   0.   9.   8.]
 [-10. -10.   0.   7.]]
